// The 346 official Chilean comunas grouped by region — used to populate
// the checkout comuna dropdown and the admin shipping-rate table. Static
// reference data (Chile's administrative divisions), not admin-editable —
// only the per-comuna PRICE (ShippingComunaRate) is.
export type ChileComuna = { region: string; comuna: string };

export const CHILE_COMUNAS: ChileComuna[] = [
  { region: "Arica y Parinacota", comuna: "Arica" },
  { region: "Arica y Parinacota", comuna: "Camarones" },
  { region: "Arica y Parinacota", comuna: "Putre" },
  { region: "Arica y Parinacota", comuna: "General Lagos" },
  { region: "Tarapacá", comuna: "Iquique" },
  { region: "Tarapacá", comuna: "Alto Hospicio" },
  { region: "Tarapacá", comuna: "Pozo Almonte" },
  { region: "Tarapacá", comuna: "Camiña" },
  { region: "Tarapacá", comuna: "Colchane" },
  { region: "Tarapacá", comuna: "Huara" },
  { region: "Tarapacá", comuna: "Pica" },
  { region: "Antofagasta", comuna: "Antofagasta" },
  { region: "Antofagasta", comuna: "Mejillones" },
  { region: "Antofagasta", comuna: "Sierra Gorda" },
  { region: "Antofagasta", comuna: "Taltal" },
  { region: "Antofagasta", comuna: "Calama" },
  { region: "Antofagasta", comuna: "Ollagüe" },
  { region: "Antofagasta", comuna: "San Pedro de Atacama" },
  { region: "Antofagasta", comuna: "Tocopilla" },
  { region: "Antofagasta", comuna: "María Elena" },
  { region: "Atacama", comuna: "Copiapó" },
  { region: "Atacama", comuna: "Caldera" },
  { region: "Atacama", comuna: "Tierra Amarilla" },
  { region: "Atacama", comuna: "Chañaral" },
  { region: "Atacama", comuna: "Diego de Almagro" },
  { region: "Atacama", comuna: "Vallenar" },
  { region: "Atacama", comuna: "Alto del Carmen" },
  { region: "Atacama", comuna: "Freirina" },
  { region: "Atacama", comuna: "Huasco" },
  { region: "Coquimbo", comuna: "La Serena" },
  { region: "Coquimbo", comuna: "Coquimbo" },
  { region: "Coquimbo", comuna: "Andacollo" },
  { region: "Coquimbo", comuna: "La Higuera" },
  { region: "Coquimbo", comuna: "Paiguano" },
  { region: "Coquimbo", comuna: "Vicuña" },
  { region: "Coquimbo", comuna: "Illapel" },
  { region: "Coquimbo", comuna: "Canela" },
  { region: "Coquimbo", comuna: "Los Vilos" },
  { region: "Coquimbo", comuna: "Salamanca" },
  { region: "Coquimbo", comuna: "Ovalle" },
  { region: "Coquimbo", comuna: "Combarbalá" },
  { region: "Coquimbo", comuna: "Monte Patria" },
  { region: "Coquimbo", comuna: "Punitaqui" },
  { region: "Coquimbo", comuna: "Río Hurtado" },
  { region: "Valparaíso", comuna: "Valparaíso" },
  { region: "Valparaíso", comuna: "Casablanca" },
  { region: "Valparaíso", comuna: "Concón" },
  { region: "Valparaíso", comuna: "Juan Fernández" },
  { region: "Valparaíso", comuna: "Puchuncaví" },
  { region: "Valparaíso", comuna: "Quintero" },
  { region: "Valparaíso", comuna: "Viña del Mar" },
  { region: "Valparaíso", comuna: "Isla de Pascua" },
  { region: "Valparaíso", comuna: "Los Andes" },
  { region: "Valparaíso", comuna: "Calle Larga" },
  { region: "Valparaíso", comuna: "Rinconada" },
  { region: "Valparaíso", comuna: "San Esteban" },
  { region: "Valparaíso", comuna: "La Ligua" },
  { region: "Valparaíso", comuna: "Cabildo" },
  { region: "Valparaíso", comuna: "Papudo" },
  { region: "Valparaíso", comuna: "Petorca" },
  { region: "Valparaíso", comuna: "Zapallar" },
  { region: "Valparaíso", comuna: "Quillota" },
  { region: "Valparaíso", comuna: "Calera" },
  { region: "Valparaíso", comuna: "Hijuelas" },
  { region: "Valparaíso", comuna: "La Cruz" },
  { region: "Valparaíso", comuna: "Nogales" },
  { region: "Valparaíso", comuna: "San Antonio" },
  { region: "Valparaíso", comuna: "Algarrobo" },
  { region: "Valparaíso", comuna: "Cartagena" },
  { region: "Valparaíso", comuna: "El Quisco" },
  { region: "Valparaíso", comuna: "El Tabo" },
  { region: "Valparaíso", comuna: "Santo Domingo" },
  { region: "Valparaíso", comuna: "San Felipe" },
  { region: "Valparaíso", comuna: "Catemu" },
  { region: "Valparaíso", comuna: "Llaillay" },
  { region: "Valparaíso", comuna: "Panquehue" },
  { region: "Valparaíso", comuna: "Putaendo" },
  { region: "Valparaíso", comuna: "Santa María" },
  { region: "Valparaíso", comuna: "Quilpué" },
  { region: "Valparaíso", comuna: "Limache" },
  { region: "Valparaíso", comuna: "Olmué" },
  { region: "Valparaíso", comuna: "Villa Alemana" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Rancagua" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Codegua" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Coinco" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Coltauco" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Doñihue" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Graneros" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Las Cabras" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Machalí" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Malloa" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Mostazal" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Olivar" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Peumo" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Pichidegua" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Quinta de Tilcoco" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Rengo" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Requínoa" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "San Vicente" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Pichilemu" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "La Estrella" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Litueche" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Marchihue" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Navidad" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Paredones" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "San Fernando" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Chépica" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Chimbarongo" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Lolol" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Nancagua" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Palmilla" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Peralillo" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Placilla" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Pumanque" },
  { region: "Región del Libertador Gral. Bernardo O’Higgins", comuna: "Santa Cruz" },
  { region: "Región del Maule", comuna: "Talca" },
  { region: "Región del Maule", comuna: "Constitución" },
  { region: "Región del Maule", comuna: "Curepto" },
  { region: "Región del Maule", comuna: "Empedrado" },
  { region: "Región del Maule", comuna: "Maule" },
  { region: "Región del Maule", comuna: "Pelarco" },
  { region: "Región del Maule", comuna: "Pencahue" },
  { region: "Región del Maule", comuna: "Río Claro" },
  { region: "Región del Maule", comuna: "San Clemente" },
  { region: "Región del Maule", comuna: "San Rafael" },
  { region: "Región del Maule", comuna: "Cauquenes" },
  { region: "Región del Maule", comuna: "Chanco" },
  { region: "Región del Maule", comuna: "Pelluhue" },
  { region: "Región del Maule", comuna: "Curicó" },
  { region: "Región del Maule", comuna: "Hualañé" },
  { region: "Región del Maule", comuna: "Licantén" },
  { region: "Región del Maule", comuna: "Molina" },
  { region: "Región del Maule", comuna: "Rauco" },
  { region: "Región del Maule", comuna: "Romeral" },
  { region: "Región del Maule", comuna: "Sagrada Familia" },
  { region: "Región del Maule", comuna: "Teno" },
  { region: "Región del Maule", comuna: "Vichuquén" },
  { region: "Región del Maule", comuna: "Linares" },
  { region: "Región del Maule", comuna: "Colbún" },
  { region: "Región del Maule", comuna: "Longaví" },
  { region: "Región del Maule", comuna: "Parral" },
  { region: "Región del Maule", comuna: "Retiro" },
  { region: "Región del Maule", comuna: "San Javier" },
  { region: "Región del Maule", comuna: "Villa Alegre" },
  { region: "Región del Maule", comuna: "Yerbas Buenas" },
  { region: "Región de Ñuble", comuna: "Cobquecura" },
  { region: "Región de Ñuble", comuna: "Coelemu" },
  { region: "Región de Ñuble", comuna: "Ninhue" },
  { region: "Región de Ñuble", comuna: "Portezuelo" },
  { region: "Región de Ñuble", comuna: "Quirihue" },
  { region: "Región de Ñuble", comuna: "Ránquil" },
  { region: "Región de Ñuble", comuna: "Treguaco" },
  { region: "Región de Ñuble", comuna: "Bulnes" },
  { region: "Región de Ñuble", comuna: "Chillán Viejo" },
  { region: "Región de Ñuble", comuna: "Chillán" },
  { region: "Región de Ñuble", comuna: "El Carmen" },
  { region: "Región de Ñuble", comuna: "Pemuco" },
  { region: "Región de Ñuble", comuna: "Pinto" },
  { region: "Región de Ñuble", comuna: "Quillón" },
  { region: "Región de Ñuble", comuna: "San Ignacio" },
  { region: "Región de Ñuble", comuna: "Yungay" },
  { region: "Región de Ñuble", comuna: "Coihueco" },
  { region: "Región de Ñuble", comuna: "Ñiquén" },
  { region: "Región de Ñuble", comuna: "San Carlos" },
  { region: "Región de Ñuble", comuna: "San Fabián" },
  { region: "Región de Ñuble", comuna: "San Nicolás" },
  { region: "Región del Biobío", comuna: "Concepción" },
  { region: "Región del Biobío", comuna: "Coronel" },
  { region: "Región del Biobío", comuna: "Chiguayante" },
  { region: "Región del Biobío", comuna: "Florida" },
  { region: "Región del Biobío", comuna: "Hualqui" },
  { region: "Región del Biobío", comuna: "Lota" },
  { region: "Región del Biobío", comuna: "Penco" },
  { region: "Región del Biobío", comuna: "San Pedro de la Paz" },
  { region: "Región del Biobío", comuna: "Santa Juana" },
  { region: "Región del Biobío", comuna: "Talcahuano" },
  { region: "Región del Biobío", comuna: "Tomé" },
  { region: "Región del Biobío", comuna: "Hualpén" },
  { region: "Región del Biobío", comuna: "Lebu" },
  { region: "Región del Biobío", comuna: "Arauco" },
  { region: "Región del Biobío", comuna: "Cañete" },
  { region: "Región del Biobío", comuna: "Contulmo" },
  { region: "Región del Biobío", comuna: "Curanilahue" },
  { region: "Región del Biobío", comuna: "Los Álamos" },
  { region: "Región del Biobío", comuna: "Tirúa" },
  { region: "Región del Biobío", comuna: "Los Ángeles" },
  { region: "Región del Biobío", comuna: "Antuco" },
  { region: "Región del Biobío", comuna: "Cabrero" },
  { region: "Región del Biobío", comuna: "Laja" },
  { region: "Región del Biobío", comuna: "Mulchén" },
  { region: "Región del Biobío", comuna: "Nacimiento" },
  { region: "Región del Biobío", comuna: "Negrete" },
  { region: "Región del Biobío", comuna: "Quilaco" },
  { region: "Región del Biobío", comuna: "Quilleco" },
  { region: "Región del Biobío", comuna: "San Rosendo" },
  { region: "Región del Biobío", comuna: "Santa Bárbara" },
  { region: "Región del Biobío", comuna: "Tucapel" },
  { region: "Región del Biobío", comuna: "Yumbel" },
  { region: "Región del Biobío", comuna: "Alto Biobío" },
  { region: "Región de la Araucanía", comuna: "Temuco" },
  { region: "Región de la Araucanía", comuna: "Carahue" },
  { region: "Región de la Araucanía", comuna: "Cunco" },
  { region: "Región de la Araucanía", comuna: "Curarrehue" },
  { region: "Región de la Araucanía", comuna: "Freire" },
  { region: "Región de la Araucanía", comuna: "Galvarino" },
  { region: "Región de la Araucanía", comuna: "Gorbea" },
  { region: "Región de la Araucanía", comuna: "Lautaro" },
  { region: "Región de la Araucanía", comuna: "Loncoche" },
  { region: "Región de la Araucanía", comuna: "Melipeuco" },
  { region: "Región de la Araucanía", comuna: "Nueva Imperial" },
  { region: "Región de la Araucanía", comuna: "Padre las Casas" },
  { region: "Región de la Araucanía", comuna: "Perquenco" },
  { region: "Región de la Araucanía", comuna: "Pitrufquén" },
  { region: "Región de la Araucanía", comuna: "Pucón" },
  { region: "Región de la Araucanía", comuna: "Saavedra" },
  { region: "Región de la Araucanía", comuna: "Teodoro Schmidt" },
  { region: "Región de la Araucanía", comuna: "Toltén" },
  { region: "Región de la Araucanía", comuna: "Vilcún" },
  { region: "Región de la Araucanía", comuna: "Villarrica" },
  { region: "Región de la Araucanía", comuna: "Cholchol" },
  { region: "Región de la Araucanía", comuna: "Angol" },
  { region: "Región de la Araucanía", comuna: "Collipulli" },
  { region: "Región de la Araucanía", comuna: "Curacautín" },
  { region: "Región de la Araucanía", comuna: "Ercilla" },
  { region: "Región de la Araucanía", comuna: "Lonquimay" },
  { region: "Región de la Araucanía", comuna: "Los Sauces" },
  { region: "Región de la Araucanía", comuna: "Lumaco" },
  { region: "Región de la Araucanía", comuna: "Purén" },
  { region: "Región de la Araucanía", comuna: "Renaico" },
  { region: "Región de la Araucanía", comuna: "Traiguén" },
  { region: "Región de la Araucanía", comuna: "Victoria" },
  { region: "Región de Los Ríos", comuna: "Valdivia" },
  { region: "Región de Los Ríos", comuna: "Corral" },
  { region: "Región de Los Ríos", comuna: "Lanco" },
  { region: "Región de Los Ríos", comuna: "Los Lagos" },
  { region: "Región de Los Ríos", comuna: "Máfil" },
  { region: "Región de Los Ríos", comuna: "Mariquina" },
  { region: "Región de Los Ríos", comuna: "Paillaco" },
  { region: "Región de Los Ríos", comuna: "Panguipulli" },
  { region: "Región de Los Ríos", comuna: "La Unión" },
  { region: "Región de Los Ríos", comuna: "Futrono" },
  { region: "Región de Los Ríos", comuna: "Lago Ranco" },
  { region: "Región de Los Ríos", comuna: "Río Bueno" },
  { region: "Región de Los Lagos", comuna: "Puerto Montt" },
  { region: "Región de Los Lagos", comuna: "Calbuco" },
  { region: "Región de Los Lagos", comuna: "Cochamó" },
  { region: "Región de Los Lagos", comuna: "Fresia" },
  { region: "Región de Los Lagos", comuna: "Frutillar" },
  { region: "Región de Los Lagos", comuna: "Los Muermos" },
  { region: "Región de Los Lagos", comuna: "Llanquihue" },
  { region: "Región de Los Lagos", comuna: "Maullín" },
  { region: "Región de Los Lagos", comuna: "Puerto Varas" },
  { region: "Región de Los Lagos", comuna: "Castro" },
  { region: "Región de Los Lagos", comuna: "Ancud" },
  { region: "Región de Los Lagos", comuna: "Chonchi" },
  { region: "Región de Los Lagos", comuna: "Curaco de Vélez" },
  { region: "Región de Los Lagos", comuna: "Dalcahue" },
  { region: "Región de Los Lagos", comuna: "Puqueldón" },
  { region: "Región de Los Lagos", comuna: "Queilén" },
  { region: "Región de Los Lagos", comuna: "Quellón" },
  { region: "Región de Los Lagos", comuna: "Quemchi" },
  { region: "Región de Los Lagos", comuna: "Quinchao" },
  { region: "Región de Los Lagos", comuna: "Osorno" },
  { region: "Región de Los Lagos", comuna: "Puerto Octay" },
  { region: "Región de Los Lagos", comuna: "Purranque" },
  { region: "Región de Los Lagos", comuna: "Puyehue" },
  { region: "Región de Los Lagos", comuna: "Río Negro" },
  { region: "Región de Los Lagos", comuna: "San Juan de la Costa" },
  { region: "Región de Los Lagos", comuna: "San Pablo" },
  { region: "Región de Los Lagos", comuna: "Chaitén" },
  { region: "Región de Los Lagos", comuna: "Futaleufú" },
  { region: "Región de Los Lagos", comuna: "Hualaihué" },
  { region: "Región de Los Lagos", comuna: "Palena" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Coihaique" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Lago Verde" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Aisén" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Cisnes" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Guaitecas" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Cochrane" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "O’Higgins" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Tortel" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Chile Chico" },
  { region: "Región Aisén del Gral. Carlos Ibáñez del Campo", comuna: "Río Ibáñez" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Punta Arenas" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Laguna Blanca" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Río Verde" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "San Gregorio" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Cabo de Hornos (Ex Navarino)" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Antártica" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Porvenir" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Primavera" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Timaukel" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Natales" },
  { region: "Región de Magallanes y de la Antártica Chilena", comuna: "Torres del Paine" },
  { region: "Región Metropolitana de Santiago", comuna: "Cerrillos" },
  { region: "Región Metropolitana de Santiago", comuna: "Cerro Navia" },
  { region: "Región Metropolitana de Santiago", comuna: "Conchalí" },
  { region: "Región Metropolitana de Santiago", comuna: "El Bosque" },
  { region: "Región Metropolitana de Santiago", comuna: "Estación Central" },
  { region: "Región Metropolitana de Santiago", comuna: "Huechuraba" },
  { region: "Región Metropolitana de Santiago", comuna: "Independencia" },
  { region: "Región Metropolitana de Santiago", comuna: "La Cisterna" },
  { region: "Región Metropolitana de Santiago", comuna: "La Florida" },
  { region: "Región Metropolitana de Santiago", comuna: "La Granja" },
  { region: "Región Metropolitana de Santiago", comuna: "La Pintana" },
  { region: "Región Metropolitana de Santiago", comuna: "La Reina" },
  { region: "Región Metropolitana de Santiago", comuna: "Las Condes" },
  { region: "Región Metropolitana de Santiago", comuna: "Lo Barnechea" },
  { region: "Región Metropolitana de Santiago", comuna: "Lo Espejo" },
  { region: "Región Metropolitana de Santiago", comuna: "Lo Prado" },
  { region: "Región Metropolitana de Santiago", comuna: "Macul" },
  { region: "Región Metropolitana de Santiago", comuna: "Maipú" },
  { region: "Región Metropolitana de Santiago", comuna: "Ñuñoa" },
  { region: "Región Metropolitana de Santiago", comuna: "Pedro Aguirre Cerda" },
  { region: "Región Metropolitana de Santiago", comuna: "Peñalolén" },
  { region: "Región Metropolitana de Santiago", comuna: "Providencia" },
  { region: "Región Metropolitana de Santiago", comuna: "Pudahuel" },
  { region: "Región Metropolitana de Santiago", comuna: "Quilicura" },
  { region: "Región Metropolitana de Santiago", comuna: "Quinta Normal" },
  { region: "Región Metropolitana de Santiago", comuna: "Recoleta" },
  { region: "Región Metropolitana de Santiago", comuna: "Renca" },
  { region: "Región Metropolitana de Santiago", comuna: "Santiago" },
  { region: "Región Metropolitana de Santiago", comuna: "San Joaquín" },
  { region: "Región Metropolitana de Santiago", comuna: "San Miguel" },
  { region: "Región Metropolitana de Santiago", comuna: "San Ramón" },
  { region: "Región Metropolitana de Santiago", comuna: "Vitacura" },
  { region: "Región Metropolitana de Santiago", comuna: "Puente Alto" },
  { region: "Región Metropolitana de Santiago", comuna: "Pirque" },
  { region: "Región Metropolitana de Santiago", comuna: "San José de Maipo" },
  { region: "Región Metropolitana de Santiago", comuna: "Colina" },
  { region: "Región Metropolitana de Santiago", comuna: "Lampa" },
  { region: "Región Metropolitana de Santiago", comuna: "Tiltil" },
  { region: "Región Metropolitana de Santiago", comuna: "San Bernardo" },
  { region: "Región Metropolitana de Santiago", comuna: "Buin" },
  { region: "Región Metropolitana de Santiago", comuna: "Calera de Tango" },
  { region: "Región Metropolitana de Santiago", comuna: "Paine" },
  { region: "Región Metropolitana de Santiago", comuna: "Melipilla" },
  { region: "Región Metropolitana de Santiago", comuna: "Alhué" },
  { region: "Región Metropolitana de Santiago", comuna: "Curacaví" },
  { region: "Región Metropolitana de Santiago", comuna: "María Pinto" },
  { region: "Región Metropolitana de Santiago", comuna: "San Pedro" },
  { region: "Región Metropolitana de Santiago", comuna: "Talagante" },
  { region: "Región Metropolitana de Santiago", comuna: "El Monte" },
  { region: "Región Metropolitana de Santiago", comuna: "Isla de Maipo" },
  { region: "Región Metropolitana de Santiago", comuna: "Padre Hurtado" },
  { region: "Región Metropolitana de Santiago", comuna: "Peñaflor" },];
